### ISSUE TITLE
Spatial Verification (divByZero)

### ISSUE THREAD

**Issue by AudreyBeard** [SU-ECE-17-7/hotspotter#13]
Taz and Eddy came across this while exploring Issue #10 

Need more information from @cheisterkamp

**Comment by cheisterkamp** [comment]
```
=============================
[fc2] Precomputing and loading features: 'test 2'
=============================
[fc2] feat_uid = '_FEAT(hesaff+sift,0_9001)_CHIP(sz750)'
[fc2]  Loading _FEAT(hesaff+sift,0_9001)_CHIP(sz750) individually
[parallel] Already computed 3 precompute_hesaff tasks
[parallel] ... No precompute_hesaff tasks left to compute!


[fc2] Loading feature: 
[fc2] Loading feature: 3/3
[fc2] Finished load of individual kpts and desc
[fc2]=============================
[algos] precompute_flann('_dcxs((3)[1]7_l2d)_FEAT(hesaff+sift,0_9001)_CHIP(sz750)'): 

tic('compute FLANN')...toc('compute FLANN')=0.0122s
[algos] precompute_flann(): save_index('flann_index__dcxs((3)[1]7_l2d)_FEAT(hesaff+sift,0_9001)_CHIP(sz750)_4kdtree_dID((2262,128)qvbpmy$~).flann')
[mf] Step 1) Assign nearest neighbors: _NN(K4+1,last,cks1024)
[mf] * assigned 866 desc from 1 chips to 4330 nearest neighbors
[mf] Step 2) Weight neighbors: _FILT(lnbnn_0.01)
Stashing key='qcx2_nns'
[mf] Step 3) Filter neighbors: _FILT(lnbnn_0.01)
[mf] * 0 assignments are invalid by thresh
[mf] * 1965 assignments are invalid by self
[mf] * 1965 are newly invalided by self
[mf] * 1965 assignments are invalid by gx
[mf] * 0 are newly invalided by gx
[mf] * Marking 1965 assignments as invalid
[mf] Step 4) Building chipmatches
[mf] Step 5) Spatial verification: _SV(1000,0.01,0.5_2,csum)
/home/noah/code/hotspotter/hotspotter/match_chips3.py:157: RuntimeWarning: divide by zero encountered in true_divide
  matchesSVER = mf.spatial_verification(hs, matchesFILT, qdat)
/home/noah/code/hotspotter/hotspotter/match_chips3.py:157: RuntimeWarning: invalid value encountered in true_divide
  matchesSVER = mf.spatial_verification(hs, matchesFILT, qdat)
/home/noah/code/hotspotter/hotspotter/match_chips3.py:157: RuntimeWarning: invalid value encountered in multiply
  matchesSVER = mf.spatial_verification(hs, matchesFILT, qdat)
/home/noah/code/hotspotter/hotspotter/match_chips3.py:157: RuntimeWarning: invalid value encountered in add
  matchesSVER = mf.spatial_verification(hs, matchesFILT, qdat)
/home/noah/code/hotspotter/hotspotter/match_chips3.py:157: RuntimeWarning: invalid value encountered in greater
  matchesSVER = mf.spatial_verification(hs, matchesFILT, qdat)
/home/noah/code/hotspotter/hotspotter/match_chips3.py:157: RuntimeWarning: invalid value encountered in less
  matchesSVER = mf.spatial_verification(hs, matchesFILT, qdat)
..x
[mf] Finished sv
[mf] Step 6) Convert chipmatch -> res
[qr] cache save: 'res_w1=@2,y0es`5;[=]_qcid=3.npz'
[*back] _populate_table('res')
[/back] finished query

Block wrapper caugt exception in 'query'
back = <hsgui.guiback.MainWindowBackend object at 0x7f2bbb569180>
Traceback (most recent call last):
  File "/home/noah/code/hotspotter/hsgui/guitools.py", line 107, in block_wrapper
    result = func(back, *args, **kwargs)
  File "/home/noah/code/hotspotter/hsgui/guiback.py", line 758, in query
    back.show_query_result(res, tx)
  File "/home/noah/code/hotspotter/hsgui/guitools.py", line 163, in drawing_wrapper
    result = func(self, *args, **kwargs)
  File "/home/noah/code/hotspotter/hsgui/guiback.py", line 287, in show_query_result
    res.show_top(back.hs, fnum=fnum, figtitle='Query View ')
  File "/home/noah/code/hotspotter/hotspotter/QueryResult.py", line 184, in show_top
    return viz.show_top(res, hs, *args, **kwargs)
  File "/home/noah/code/hotspotter/hsviz/viz.py", line 581, in show_top
    all_kpts=False, **kwargs)
  File "/home/noah/code/hotspotter/hsviz/viz.py", line 673, in _show_res
    _color_list = df2.distinct_colors(len(topN_cxs))
  File "/home/noah/code/hotspotter/hsviz/draw_func2.py", line 213, in distinct_colors
    deterministic_shuffle(RGB_tuples)
  File "/home/noah/code/hotspotter/hsviz/draw_func2.py", line 204, in deterministic_shuffle
    np.random.seed(randS)
  File "mtrand.pyx", line 680, in mtrand.RandomState.seed (numpy/random/mtrand/mtrand.c:13729)
ValueError: Seed must be between 0 and 2**32 - 1

Traceback (most recent call last):
  File "/home/noah/code/hotspotter/hsgui/guitools.py", line 85, in slot_wrapper
    result = func(self, *args, **kwargs)
  File "/home/noah/code/hotspotter/hsgui/guitools.py", line 107, in block_wrapper
    result = func(back, *args, **kwargs)
  File "/home/noah/code/hotspotter/hsgui/guiback.py", line 758, in query
    back.show_query_result(res, tx)
  File "/home/noah/code/hotspotter/hsgui/guitools.py", line 163, in drawing_wrapper
    result = func(self, *args, **kwargs)
  File "/home/noah/code/hotspotter/hsgui/guiback.py", line 287, in show_query_result
    res.show_top(back.hs, fnum=fnum, figtitle='Query View ')
  File "/home/noah/code/hotspotter/hotspotter/QueryResult.py", line 184, in show_top
    return viz.show_top(res, hs, *args, **kwargs)
  File "/home/noah/code/hotspotter/hsviz/viz.py", line 581, in show_top
    all_kpts=False, **kwargs)
  File "/home/noah/code/hotspotter/hsviz/viz.py", line 673, in _show_res
    _color_list = df2.distinct_colors(len(topN_cxs))
  File "/home/noah/code/hotspotter/hsviz/draw_func2.py", line 213, in distinct_colors
    deterministic_shuffle(RGB_tuples)
  File "/home/noah/code/hotspotter/hsviz/draw_func2.py", line 204, in deterministic_shuffle
    np.random.seed(randS)
  File "mtrand.pyx", line 680, in mtrand.RandomState.seed (numpy/random/mtrand/mtrand.c:13729)
ValueError: Seed must be between 0 and 2**32 - 1
```
